### ISSUE TITLE
How does the catalog handle partitioned data/output?

### ISSUE THREAD

**Issue by ravwojdyla** [related-sciences/public-data-source#8]
For partitioned data (ex: `part-...`) how does the current implementation handle that? Also about GCS, which is not a file system (specifically there is not atomic "directory" move op), it is a good idea to always name files with `part-X-of-Y`, this is a great pattern because it captures information about dataset completeness/partitions for almost free.

**Comment by eric-czech** [comment]
I hadn't added anything to take control or have much awareness of file names.  Most of the datasets I stored are directories and it was up to whatever uploaded them to create the filenames (so just `part-<whatever>` with Spark).  I was thinking of the catalog entry as more like a pointer to folder that could contain anything underneath, with no restrictions on whatever made the upload easiest to use downstream.

**Comment by ravwojdyla** [comment]
@eric-czech I see, that point to the directory is very similar to the idea in #7 too, but I was confused by the `ARTIFACT_FILENAME` (I understand that the name could be set to say `part-*` or even `*`), but still if the point is to reference to directory why not skip it completely, or maybe it should be `file_pattern` instead of a name? We can go back to this point later when we discuss #7 btw.

**Comment by eric-czech** [comment]
Ah `ARTIFACT_FILENAME` is just the constant value I'm assigning to directory names.  It's usually just "data" so there would be a "data.parquet" directory that contains the part files.  The filename itself would never be assigned as a glob or anything like that (i.e. `DEFAULT_ARTIFACT_NAME` would have been a better variable).  "why not skip it completely" is what I'm doing if I'm understanding you.

**Comment by ravwojdyla** [comment]
@eric-czech oh - I see. That makes sense, sorry was confused about the naming there. In that case we can close this issue for now, and talk more in #7.
